# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615560

name: 'CMake (Windows /std)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/*'
      - '.nuget/*'
      - build/*.ps1

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        build_type: [x64-Debug, x64-Release, x64-Debug-Clang, x64-Release-Clang]
        arch: [amd64]
        include:
          - build_type: x86-Debug
            arch: amd64_x86
          - build_type: x86-Release
            arch: amd64_x86
          - build_type: arm64-Debug
            arch: amd64_arm64
          - build_type: arm64-Release
            arch: amd64_arm64
          - build_type: arm64ec-Debug
            arch: amd64_arm64
          - build_type: arm64ec-Release
            arch: amd64_arm64
          - build_type: x86-Debug-Clang
            arch: amd64_x86
          - build_type: x86-Release-Clang
            arch: amd64_x86
          - build_type: arm64-Debug-Clang
            arch: amd64_arm64
          - build_type: arm64-Release-Clang
            arch: amd64_arm64

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Clone test repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: walbourn/directxmathtest
        path: Tests
        ref: main

    - name: 'Install Ninja'
      run: choco install ninja

    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      with:
        arch: ${{ matrix.arch }}

    - name: 'Configure CMake (C++17)'
      working-directory: ${{ github.workspace }}
      run: cmake --preset=${{ matrix.build_type }}

    - name: 'Build (C++17)'
      working-directory: ${{ github.workspace }}
      run: cmake --build out\build\${{ matrix.build_type }}

    - name: 'Clean up'
      working-directory: ${{ github.workspace }}
      run: Remove-Item -Path out -Recurse -Force

    - name: 'Configure CMake (C++11)'
      working-directory: ${{ github.workspace }}
      run: cmake --preset=${{ matrix.build_type }} -DBUILD_CXX11=ON

    - name: 'Build (C++11)'
      working-directory: ${{ github.workspace }}
      run: cmake --build out\build\${{ matrix.build_type }}

    - name: 'Clean up'
      working-directory: ${{ github.workspace }}
      run: Remove-Item -Path out -Recurse -Force

    - name: 'Configure CMake (C++14)'
      working-directory: ${{ github.workspace }}
      run: cmake --preset=${{ matrix.build_type }} -DBUILD_CXX14=ON

    - name: 'Build (C++14)'
      working-directory: ${{ github.workspace }}
      run: cmake --build out\build\${{ matrix.build_type }}

    - name: 'Clean up'
      working-directory: ${{ github.workspace }}
      run: Remove-Item -Path out -Recurse -Force

    - name: 'Configure CMake (C++20)'
      working-directory: ${{ github.workspace }}
      run: cmake --preset=${{ matrix.build_type }} -DBUILD_CXX20=ON

    - name: 'Build (C++20)'
      working-directory: ${{ github.workspace }}
      run: cmake --build out\build\${{ matrix.build_type }}
