# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615560

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/*'
      - '.nuget/*'
      - build/*

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-${{ matrix.vs }}

    strategy:
      fail-fast: false

      matrix:
        vs: [2019, 2022]
        build_type: [Debug, Release, 'NI Debug', 'NI Release']
        platform: [x86, x64, ARM64]
        exclude:
        - vs: 2019
          platform: ARM64

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Clone test repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: walbourn/directxmathtest
        path: Tests
        ref: main

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

    - name: Build math3
      working-directory: ${{ github.workspace }}/Tests/math3
      run: msbuild /m /p:Configuration="${{ matrix.build_type }}" /p:Platform=${{ matrix.platform }} ./math3_${{ matrix.vs }}.sln

    - if: (matrix.build_type == 'Debug') || (matrix.build_type == 'Release')
      name: Build shmath
      working-directory: ${{ github.workspace }}/Tests/shmath
      run: msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }} ./shmath_${{ matrix.vs }}.sln

    - if: (matrix.build_type == 'Debug') || (matrix.build_type == 'Release')
      name: Build xdsp
      working-directory: ${{ github.workspace }}/Tests/xdsp
      run: msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }} ./XDSPTest_${{ matrix.vs }}.sln
