# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615560

name: 'CMake (WSL)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/*'
      - '.nuget/*'
      - build/*.ps1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [x64-Debug-Linux, x64-Release-Linux]
        gcc: [12, 13, 14]
        # x64-Debug-NI-Linux, x64-Release-NI-Linux trigger issue with GCC

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Clone test repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: walbourn/directxmathtest
        path: Tests
        ref: main

    - uses: seanmiddleditch/gha-setup-ninja@3b1f8f94a2f8254bd26914c4ab9474d4f0015f67 # v6

    - name: 'Configure CMake'
      working-directory: ${{ github.workspace }}/Tests
      run: cmake --preset=${{ matrix.build_type }}
      env:
        CC: gcc-${{ matrix.gcc }}
        CXX: g++-${{ matrix.gcc }}

    - name: 'Build'
      working-directory: ${{ github.workspace }}/Tests
      run: cmake --build out/build/${{ matrix.build_type }}
