# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=615560

name: 'CMake (WSL)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.nuget/*'
      - build/*.ps1
      - build/*.yml

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [x64-Debug-Linux, x64-Release-Linux, x64-Debug-NI-Linux, x64-Release-NI-Linux]
        gcc: [10, 11, 12]
        # x64-Debug-NI-Linux, x64-Release-NI-Linux trigger issue with GCC 11.4 CRT

    steps:
    - uses: actions/checkout@v4

    - name: Clone test repository
      uses: actions/checkout@v4
      with:
        repository: walbourn/directxmathtest
        path: Tests
        ref: main

    - uses: seanmiddleditch/gha-setup-ninja@v5

    - name: 'Configure CMake'
      working-directory: ${{ github.workspace }}/Tests
      run: cmake --preset=${{ matrix.build_type }}
      env:
        CC: gcc-${{ matrix.gcc }}
        CXX: g++-${{ matrix.gcc }}

    - name: 'Build'
      working-directory: ${{ github.workspace }}/Tests
      run: cmake --build out/build/${{ matrix.build_type }}
